name: Update Task Status

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Status
          values: In Progress
          github_token: ${{ secrets.MOVE_ASSIGNED_TASKS_TOKEN }}
          project_url: https://github.com/orgs/gmuGADIG/projects/9
          
